### ISSUE TITLE
Global is not defined error

### ISSUE THREAD

**Issue by teejayhh** [sethbrasile/ember-audio#63]
Hi I am having difficulty getting your example working -- http://sethbrasile.github.io/ember-audio/

```js
rollbar.js:26 Uncaught ReferenceError: global is not defined
    at eval (index.js:1)
    at Object.../../node_modules/base-audio-context/index.js (vendor-suffix.js:1)
    at __webpack_require__ (vendor-suffix.js:1)
    at eval (index.js:2)
    at Object.../../node_modules/stereo-panner-node/index.js (vendor-suffix.js:1)
    at __webpack_require__ (vendor-suffix.js:1)
    at Module.eval [as callback] (app.js:25)
    at Module.exports (loader.js:106)
    at Module._reify (loader.js:143)
    at Module.reify (loader.js:130)
```

the index.js from `base-audio-context`

```js
var AudioContext = global.AudioContext || global.webkitAudioContext;
var OfflineAudioContext = global.OfflineAudioContext || global.webkitOfflineAudioContext;
var BaseAudioContext = global.BaseAudioContext || OfflineAudioContext && Object.getPrototypeOf(OfflineAudioContext);
module.exports = typeof BaseAudioContext === "function" && BaseAudioContext.prototype ? BaseAudioContext : AudioContext;
```

How could we fix it?

**Comment by sethbrasile** [comment]
The code example you provided is not code inside this repository, it's the "built" code after it has been transpiled by ember-cli's build tools, right? I'm not certain why your example is using `global`... In my project, It looks like you're trying to run it in some nonstandard environment or browser or run it through some nonstandard build tool?

Are you running this code in node instead of a browser? Maybe in fastboot? I haven't done any testing in fastboot.

I'm closing this. Please reopen if you want to provide further information.

**Comment by saravanak** [comment]
fwiw, I made this change on `ember-cli-build.js` and it worked. 

```
    autoImport: {
      webpack: {
        node: {
          global: true
        }
      }
    },
```
Details:  
[ember-auto-import help](https://github.com/ef4/ember-auto-import#i-upgraded-my-ember-auto-import-version-and-now-things-dont-import-what-changed)

**Comment by sethbrasile** [comment]
Thank you @saravanak!
